package user.card.generator.domain.person;

public enum PersonCategory {
    RETIRED_USE_CARD_AND_INTERNET,
    RETIRED_DONT_USE_CARD_AND_INTERNET,
    ORDINARYUSER_USE_CARD_AND_INTERNET,
    ORDINARY_USER_USE_CARD_DONT_USE_INTERNET,
    ORDINARY_USER_DONT_USE_CARD,
    VIP_USER
}
