create table transaction
(
    id               bigint not null auto_increment,
    card_number      varchar(255),
    transaction_type integer,
    timestamp        datetime(6),
    amount           integer,
    currency_name    varchar(255),
    response_code    integer,
    country_name     varchar(255),
    vendor_code      varchar(255),
    field1           double precision,
    field2           double precision,
    field3           double precision,
    field4           double precision,
    field5           double precision,
    field6           double precision,
    field7           double precision,
    field8           double precision,
    field9           double precision,
    field10          double precision,
    field11          double precision,
    field12          double precision,
    field13          double precision,
    field14          double precision,
    field15          double precision,
    field16          double precision,
    field17          double precision,
    field18          double precision,
    field19          double precision,
    field20          double precision,
    field21          double precision,
    field22          double precision,
    field23          double precision,
    field24          double precision,
    field25          double precision,
    field26          varchar(255),
    field27          varchar(255),
    field28          varchar(255),
    field29          varchar(255),
    field30          varchar(255),
    field31          varchar(255),
    field32          varchar(255),
    field33          varchar(255),
    field34          varchar(255),
    field35          varchar(255),
    field36          date,
    field37          date,
    field38          date,
    field39          date,
    field40          date,
    fraud            int,
    primary key (id)
) engine = InnoDB
